services:
    # ADAPTERS
    options.adapater.doctrine:
        class: Damian972\OptionsBundle\Adapter\DoctrineAdapter
        arguments: ['@doctrine.orm.entity_manager']

    Damian972\OptionsBundle\Contracts\AdapterInterface: '@options.adapater.doctrine'

    # SERVICES
    options.service:
        public: true
        class: Damian972\OptionsBundle\Options
        arguments: ['@Damian972\OptionsBundle\Contracts\AdapterInterface', '%options.lazy%']

    Damian972\OptionsBundle\Options: '@options.service'
